Make xrange py3 compatible
In py3 ,
Xrange is renamed to range,
so it needs to be modified to make it compatible.
the code:
print (xrange(5))
Traceback (most recent call last):
  File "code", line 4, in <module>
    print (xrange(5))
NameError: name 'xrange' is not defined.

Change-Id: I3a0e22876c35ced5c961c092fcda25db33d1c599
Closes-Bug: #1596127